swagger: "2.0"
info:
  title: Swagger
  version: 0.1.0
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /employee/salary_statement:
    get:
      tags:
        - get_salary_statement_for_employee
      description: 従業員が特定の年月の給料明細書を取得するためのAPI
      parameters:
        - name: year_month
          in: query
          description: 取得しようとしている給料明細書の年月
          required: true
          type: string
          format: yyyy-MM
      responses:
        200:
          description: OK