// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetUnprotectedHandlerFunc turns a function with the right signature into a get unprotected handler
type GetUnprotectedHandlerFunc func(GetUnprotectedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUnprotectedHandlerFunc) Handle(params GetUnprotectedParams) middleware.Responder {
	return fn(params)
}

// GetUnprotectedHandler interface for that can handle valid get unprotected params
type GetUnprotectedHandler interface {
	Handle(GetUnprotectedParams) middleware.Responder
}

// NewGetUnprotected creates a new http.Handler for the get unprotected operation
func NewGetUnprotected(ctx *middleware.Context, handler GetUnprotectedHandler) *GetUnprotected {
	return &GetUnprotected{Context: ctx, Handler: handler}
}

/*
	GetUnprotected swagger:route GET /unprotected getUnprotected

誰でも実行できるお試しAPI
*/
type GetUnprotected struct {
	Context *middleware.Context
	Handler GetUnprotectedHandler
}

func (o *GetUnprotected) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUnprotectedParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetUnprotectedOKBody get unprotected o k body
//
// swagger:model GetUnprotectedOKBody
type GetUnprotectedOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get unprotected o k body
func (o *GetUnprotectedOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get unprotected o k body based on context it is used
func (o *GetUnprotectedOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetUnprotectedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetUnprotectedOKBody) UnmarshalBinary(b []byte) error {
	var res GetUnprotectedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
