// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetAdministratorProtectedHandlerFunc turns a function with the right signature into a get administrator protected handler
type GetAdministratorProtectedHandlerFunc func(GetAdministratorProtectedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAdministratorProtectedHandlerFunc) Handle(params GetAdministratorProtectedParams) middleware.Responder {
	return fn(params)
}

// GetAdministratorProtectedHandler interface for that can handle valid get administrator protected params
type GetAdministratorProtectedHandler interface {
	Handle(GetAdministratorProtectedParams) middleware.Responder
}

// NewGetAdministratorProtected creates a new http.Handler for the get administrator protected operation
func NewGetAdministratorProtected(ctx *middleware.Context, handler GetAdministratorProtectedHandler) *GetAdministratorProtected {
	return &GetAdministratorProtected{Context: ctx, Handler: handler}
}

/*
	GetAdministratorProtected swagger:route GET /administrator/protected getAdministratorProtected

登録済みの管理者のみ実行可能なお試しAPI
*/
type GetAdministratorProtected struct {
	Context *middleware.Context
	Handler GetAdministratorProtectedHandler
}

func (o *GetAdministratorProtected) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAdministratorProtectedParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetAdministratorProtectedInternalServerErrorBody get administrator protected internal server error body
//
// swagger:model GetAdministratorProtectedInternalServerErrorBody
type GetAdministratorProtectedInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get administrator protected internal server error body
func (o *GetAdministratorProtectedInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get administrator protected internal server error body based on context it is used
func (o *GetAdministratorProtectedInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAdministratorProtectedInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdministratorProtectedInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res GetAdministratorProtectedInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetAdministratorProtectedOKBody get administrator protected o k body
//
// swagger:model GetAdministratorProtectedOKBody
type GetAdministratorProtectedOKBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get administrator protected o k body
func (o *GetAdministratorProtectedOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get administrator protected o k body based on context it is used
func (o *GetAdministratorProtectedOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAdministratorProtectedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdministratorProtectedOKBody) UnmarshalBinary(b []byte) error {
	var res GetAdministratorProtectedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetAdministratorProtectedUnauthorizedBody get administrator protected unauthorized body
//
// swagger:model GetAdministratorProtectedUnauthorizedBody
type GetAdministratorProtectedUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this get administrator protected unauthorized body
func (o *GetAdministratorProtectedUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get administrator protected unauthorized body based on context it is used
func (o *GetAdministratorProtectedUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAdministratorProtectedUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAdministratorProtectedUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res GetAdministratorProtectedUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
