// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAdministratorProtectedOKCode is the HTTP code returned for type GetAdministratorProtectedOK
const GetAdministratorProtectedOKCode int = 200

/*
GetAdministratorProtectedOK OK

swagger:response getAdministratorProtectedOK
*/
type GetAdministratorProtectedOK struct {

	/*
	  In: Body
	*/
	Payload *GetAdministratorProtectedOKBody `json:"body,omitempty"`
}

// NewGetAdministratorProtectedOK creates GetAdministratorProtectedOK with default headers values
func NewGetAdministratorProtectedOK() *GetAdministratorProtectedOK {

	return &GetAdministratorProtectedOK{}
}

// WithPayload adds the payload to the get administrator protected o k response
func (o *GetAdministratorProtectedOK) WithPayload(payload *GetAdministratorProtectedOKBody) *GetAdministratorProtectedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get administrator protected o k response
func (o *GetAdministratorProtectedOK) SetPayload(payload *GetAdministratorProtectedOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdministratorProtectedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdministratorProtectedUnauthorizedCode is the HTTP code returned for type GetAdministratorProtectedUnauthorized
const GetAdministratorProtectedUnauthorizedCode int = 401

/*
GetAdministratorProtectedUnauthorized Unauthorized

swagger:response getAdministratorProtectedUnauthorized
*/
type GetAdministratorProtectedUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *GetAdministratorProtectedUnauthorizedBody `json:"body,omitempty"`
}

// NewGetAdministratorProtectedUnauthorized creates GetAdministratorProtectedUnauthorized with default headers values
func NewGetAdministratorProtectedUnauthorized() *GetAdministratorProtectedUnauthorized {

	return &GetAdministratorProtectedUnauthorized{}
}

// WithPayload adds the payload to the get administrator protected unauthorized response
func (o *GetAdministratorProtectedUnauthorized) WithPayload(payload *GetAdministratorProtectedUnauthorizedBody) *GetAdministratorProtectedUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get administrator protected unauthorized response
func (o *GetAdministratorProtectedUnauthorized) SetPayload(payload *GetAdministratorProtectedUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdministratorProtectedUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAdministratorProtectedInternalServerErrorCode is the HTTP code returned for type GetAdministratorProtectedInternalServerError
const GetAdministratorProtectedInternalServerErrorCode int = 500

/*
GetAdministratorProtectedInternalServerError Internal Server Error

swagger:response getAdministratorProtectedInternalServerError
*/
type GetAdministratorProtectedInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *GetAdministratorProtectedInternalServerErrorBody `json:"body,omitempty"`
}

// NewGetAdministratorProtectedInternalServerError creates GetAdministratorProtectedInternalServerError with default headers values
func NewGetAdministratorProtectedInternalServerError() *GetAdministratorProtectedInternalServerError {

	return &GetAdministratorProtectedInternalServerError{}
}

// WithPayload adds the payload to the get administrator protected internal server error response
func (o *GetAdministratorProtectedInternalServerError) WithPayload(payload *GetAdministratorProtectedInternalServerErrorBody) *GetAdministratorProtectedInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get administrator protected internal server error response
func (o *GetAdministratorProtectedInternalServerError) SetPayload(payload *GetAdministratorProtectedInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAdministratorProtectedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
