// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAdministratorSalaryStatementIndividualCreatedCode is the HTTP code returned for type PostAdministratorSalaryStatementIndividualCreated
const PostAdministratorSalaryStatementIndividualCreatedCode int = 201

/*
PostAdministratorSalaryStatementIndividualCreated Created

swagger:response postAdministratorSalaryStatementIndividualCreated
*/
type PostAdministratorSalaryStatementIndividualCreated struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementIndividualCreatedBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementIndividualCreated creates PostAdministratorSalaryStatementIndividualCreated with default headers values
func NewPostAdministratorSalaryStatementIndividualCreated() *PostAdministratorSalaryStatementIndividualCreated {

	return &PostAdministratorSalaryStatementIndividualCreated{}
}

// WithPayload adds the payload to the post administrator salary statement individual created response
func (o *PostAdministratorSalaryStatementIndividualCreated) WithPayload(payload *PostAdministratorSalaryStatementIndividualCreatedBody) *PostAdministratorSalaryStatementIndividualCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement individual created response
func (o *PostAdministratorSalaryStatementIndividualCreated) SetPayload(payload *PostAdministratorSalaryStatementIndividualCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementIndividualCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementIndividualBadRequestCode is the HTTP code returned for type PostAdministratorSalaryStatementIndividualBadRequest
const PostAdministratorSalaryStatementIndividualBadRequestCode int = 400

/*
PostAdministratorSalaryStatementIndividualBadRequest BadRequest

swagger:response postAdministratorSalaryStatementIndividualBadRequest
*/
type PostAdministratorSalaryStatementIndividualBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementIndividualBadRequestBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementIndividualBadRequest creates PostAdministratorSalaryStatementIndividualBadRequest with default headers values
func NewPostAdministratorSalaryStatementIndividualBadRequest() *PostAdministratorSalaryStatementIndividualBadRequest {

	return &PostAdministratorSalaryStatementIndividualBadRequest{}
}

// WithPayload adds the payload to the post administrator salary statement individual bad request response
func (o *PostAdministratorSalaryStatementIndividualBadRequest) WithPayload(payload *PostAdministratorSalaryStatementIndividualBadRequestBody) *PostAdministratorSalaryStatementIndividualBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement individual bad request response
func (o *PostAdministratorSalaryStatementIndividualBadRequest) SetPayload(payload *PostAdministratorSalaryStatementIndividualBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementIndividualBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementIndividualUnauthorizedCode is the HTTP code returned for type PostAdministratorSalaryStatementIndividualUnauthorized
const PostAdministratorSalaryStatementIndividualUnauthorizedCode int = 401

/*
PostAdministratorSalaryStatementIndividualUnauthorized Unauthorized

swagger:response postAdministratorSalaryStatementIndividualUnauthorized
*/
type PostAdministratorSalaryStatementIndividualUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementIndividualUnauthorizedBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementIndividualUnauthorized creates PostAdministratorSalaryStatementIndividualUnauthorized with default headers values
func NewPostAdministratorSalaryStatementIndividualUnauthorized() *PostAdministratorSalaryStatementIndividualUnauthorized {

	return &PostAdministratorSalaryStatementIndividualUnauthorized{}
}

// WithPayload adds the payload to the post administrator salary statement individual unauthorized response
func (o *PostAdministratorSalaryStatementIndividualUnauthorized) WithPayload(payload *PostAdministratorSalaryStatementIndividualUnauthorizedBody) *PostAdministratorSalaryStatementIndividualUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement individual unauthorized response
func (o *PostAdministratorSalaryStatementIndividualUnauthorized) SetPayload(payload *PostAdministratorSalaryStatementIndividualUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementIndividualUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementIndividualInternalServerErrorCode is the HTTP code returned for type PostAdministratorSalaryStatementIndividualInternalServerError
const PostAdministratorSalaryStatementIndividualInternalServerErrorCode int = 500

/*
PostAdministratorSalaryStatementIndividualInternalServerError Internal Server Error

swagger:response postAdministratorSalaryStatementIndividualInternalServerError
*/
type PostAdministratorSalaryStatementIndividualInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementIndividualInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementIndividualInternalServerError creates PostAdministratorSalaryStatementIndividualInternalServerError with default headers values
func NewPostAdministratorSalaryStatementIndividualInternalServerError() *PostAdministratorSalaryStatementIndividualInternalServerError {

	return &PostAdministratorSalaryStatementIndividualInternalServerError{}
}

// WithPayload adds the payload to the post administrator salary statement individual internal server error response
func (o *PostAdministratorSalaryStatementIndividualInternalServerError) WithPayload(payload *PostAdministratorSalaryStatementIndividualInternalServerErrorBody) *PostAdministratorSalaryStatementIndividualInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement individual internal server error response
func (o *PostAdministratorSalaryStatementIndividualInternalServerError) SetPayload(payload *PostAdministratorSalaryStatementIndividualInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementIndividualInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
