// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostAdministratorSalaryStatementCreatedCode is the HTTP code returned for type PostAdministratorSalaryStatementCreated
const PostAdministratorSalaryStatementCreatedCode int = 201

/*
PostAdministratorSalaryStatementCreated Created

swagger:response postAdministratorSalaryStatementCreated
*/
type PostAdministratorSalaryStatementCreated struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementCreatedBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementCreated creates PostAdministratorSalaryStatementCreated with default headers values
func NewPostAdministratorSalaryStatementCreated() *PostAdministratorSalaryStatementCreated {

	return &PostAdministratorSalaryStatementCreated{}
}

// WithPayload adds the payload to the post administrator salary statement created response
func (o *PostAdministratorSalaryStatementCreated) WithPayload(payload *PostAdministratorSalaryStatementCreatedBody) *PostAdministratorSalaryStatementCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement created response
func (o *PostAdministratorSalaryStatementCreated) SetPayload(payload *PostAdministratorSalaryStatementCreatedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementBadRequestCode is the HTTP code returned for type PostAdministratorSalaryStatementBadRequest
const PostAdministratorSalaryStatementBadRequestCode int = 400

/*
PostAdministratorSalaryStatementBadRequest BadRequest

swagger:response postAdministratorSalaryStatementBadRequest
*/
type PostAdministratorSalaryStatementBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementBadRequestBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementBadRequest creates PostAdministratorSalaryStatementBadRequest with default headers values
func NewPostAdministratorSalaryStatementBadRequest() *PostAdministratorSalaryStatementBadRequest {

	return &PostAdministratorSalaryStatementBadRequest{}
}

// WithPayload adds the payload to the post administrator salary statement bad request response
func (o *PostAdministratorSalaryStatementBadRequest) WithPayload(payload *PostAdministratorSalaryStatementBadRequestBody) *PostAdministratorSalaryStatementBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement bad request response
func (o *PostAdministratorSalaryStatementBadRequest) SetPayload(payload *PostAdministratorSalaryStatementBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementUnauthorizedCode is the HTTP code returned for type PostAdministratorSalaryStatementUnauthorized
const PostAdministratorSalaryStatementUnauthorizedCode int = 401

/*
PostAdministratorSalaryStatementUnauthorized Unauthorized

swagger:response postAdministratorSalaryStatementUnauthorized
*/
type PostAdministratorSalaryStatementUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementUnauthorizedBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementUnauthorized creates PostAdministratorSalaryStatementUnauthorized with default headers values
func NewPostAdministratorSalaryStatementUnauthorized() *PostAdministratorSalaryStatementUnauthorized {

	return &PostAdministratorSalaryStatementUnauthorized{}
}

// WithPayload adds the payload to the post administrator salary statement unauthorized response
func (o *PostAdministratorSalaryStatementUnauthorized) WithPayload(payload *PostAdministratorSalaryStatementUnauthorizedBody) *PostAdministratorSalaryStatementUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement unauthorized response
func (o *PostAdministratorSalaryStatementUnauthorized) SetPayload(payload *PostAdministratorSalaryStatementUnauthorizedBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAdministratorSalaryStatementInternalServerErrorCode is the HTTP code returned for type PostAdministratorSalaryStatementInternalServerError
const PostAdministratorSalaryStatementInternalServerErrorCode int = 500

/*
PostAdministratorSalaryStatementInternalServerError Internal Server Error

swagger:response postAdministratorSalaryStatementInternalServerError
*/
type PostAdministratorSalaryStatementInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *PostAdministratorSalaryStatementInternalServerErrorBody `json:"body,omitempty"`
}

// NewPostAdministratorSalaryStatementInternalServerError creates PostAdministratorSalaryStatementInternalServerError with default headers values
func NewPostAdministratorSalaryStatementInternalServerError() *PostAdministratorSalaryStatementInternalServerError {

	return &PostAdministratorSalaryStatementInternalServerError{}
}

// WithPayload adds the payload to the post administrator salary statement internal server error response
func (o *PostAdministratorSalaryStatementInternalServerError) WithPayload(payload *PostAdministratorSalaryStatementInternalServerErrorBody) *PostAdministratorSalaryStatementInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post administrator salary statement internal server error response
func (o *PostAdministratorSalaryStatementInternalServerError) SetPayload(payload *PostAdministratorSalaryStatementInternalServerErrorBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAdministratorSalaryStatementInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
