// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"usr/local/go/swagger/models"
)

// NewPostAdministratorSalaryStatementIndividualParams creates a new PostAdministratorSalaryStatementIndividualParams object
//
// There are no default values defined in the spec.
func NewPostAdministratorSalaryStatementIndividualParams() PostAdministratorSalaryStatementIndividualParams {

	return PostAdministratorSalaryStatementIndividualParams{}
}

// PostAdministratorSalaryStatementIndividualParams contains all the bound params for the post administrator salary statement individual operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAdministratorSalaryStatementIndividual
type PostAdministratorSalaryStatementIndividualParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*給料明細のリクエストデータ
	  Required: true
	  In: body
	*/
	SalaryStatementRequest *models.SalaryStatementRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAdministratorSalaryStatementIndividualParams() beforehand.
func (o *PostAdministratorSalaryStatementIndividualParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.SalaryStatementRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("salaryStatementRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("salaryStatementRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.SalaryStatementRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("salaryStatementRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
