// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostAdministratorSalaryStatementHandlerFunc turns a function with the right signature into a post administrator salary statement handler
type PostAdministratorSalaryStatementHandlerFunc func(PostAdministratorSalaryStatementParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAdministratorSalaryStatementHandlerFunc) Handle(params PostAdministratorSalaryStatementParams) middleware.Responder {
	return fn(params)
}

// PostAdministratorSalaryStatementHandler interface for that can handle valid post administrator salary statement params
type PostAdministratorSalaryStatementHandler interface {
	Handle(PostAdministratorSalaryStatementParams) middleware.Responder
}

// NewPostAdministratorSalaryStatement creates a new http.Handler for the post administrator salary statement operation
func NewPostAdministratorSalaryStatement(ctx *middleware.Context, handler PostAdministratorSalaryStatementHandler) *PostAdministratorSalaryStatement {
	return &PostAdministratorSalaryStatement{Context: ctx, Handler: handler}
}

/*
	PostAdministratorSalaryStatement swagger:route POST /administrator/salary_statement postAdministratorSalaryStatement

特定の年と月の給料明細を個別支給・個別控除を利用して作成するための管理者向けAPI
*/
type PostAdministratorSalaryStatement struct {
	Context *middleware.Context
	Handler PostAdministratorSalaryStatementHandler
}

func (o *PostAdministratorSalaryStatement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAdministratorSalaryStatementParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostAdministratorSalaryStatementBadRequestBody post administrator salary statement bad request body
//
// swagger:model PostAdministratorSalaryStatementBadRequestBody
type PostAdministratorSalaryStatementBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post administrator salary statement bad request body
func (o *PostAdministratorSalaryStatementBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post administrator salary statement bad request body based on context it is used
func (o *PostAdministratorSalaryStatementBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostAdministratorSalaryStatementBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostAdministratorSalaryStatementCreatedBody post administrator salary statement created body
//
// swagger:model PostAdministratorSalaryStatementCreatedBody
type PostAdministratorSalaryStatementCreatedBody struct {

	// 給料明細id
	IDOfSalaryStatement int64 `json:"id_of_salary_statement,omitempty"`
}

// Validate validates this post administrator salary statement created body
func (o *PostAdministratorSalaryStatementCreatedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post administrator salary statement created body based on context it is used
func (o *PostAdministratorSalaryStatementCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementCreatedBody) UnmarshalBinary(b []byte) error {
	var res PostAdministratorSalaryStatementCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostAdministratorSalaryStatementInternalServerErrorBody post administrator salary statement internal server error body
//
// swagger:model PostAdministratorSalaryStatementInternalServerErrorBody
type PostAdministratorSalaryStatementInternalServerErrorBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post administrator salary statement internal server error body
func (o *PostAdministratorSalaryStatementInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post administrator salary statement internal server error body based on context it is used
func (o *PostAdministratorSalaryStatementInternalServerErrorBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res PostAdministratorSalaryStatementInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostAdministratorSalaryStatementUnauthorizedBody post administrator salary statement unauthorized body
//
// swagger:model PostAdministratorSalaryStatementUnauthorizedBody
type PostAdministratorSalaryStatementUnauthorizedBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post administrator salary statement unauthorized body
func (o *PostAdministratorSalaryStatementUnauthorizedBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post administrator salary statement unauthorized body based on context it is used
func (o *PostAdministratorSalaryStatementUnauthorizedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementUnauthorizedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostAdministratorSalaryStatementUnauthorizedBody) UnmarshalBinary(b []byte) error {
	var res PostAdministratorSalaryStatementUnauthorizedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
