// Code generated by go-swagger; DO NOT EDIT.

package get_salary_statement_for_employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetEmployeeSalaryStatementParams creates a new GetEmployeeSalaryStatementParams object
//
// There are no default values defined in the spec.
func NewGetEmployeeSalaryStatementParams() GetEmployeeSalaryStatementParams {

	return GetEmployeeSalaryStatementParams{}
}

// GetEmployeeSalaryStatementParams contains all the bound params for the get employee salary statement operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetEmployeeSalaryStatement
type GetEmployeeSalaryStatementParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*取得しようとしている給料明細書の年月
	  Required: true
	  In: query
	*/
	YearMonth string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEmployeeSalaryStatementParams() beforehand.
func (o *GetEmployeeSalaryStatementParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qYearMonth, qhkYearMonth, _ := qs.GetOK("year_month")
	if err := o.bindYearMonth(qYearMonth, qhkYearMonth, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindYearMonth binds and validates parameter YearMonth from query.
func (o *GetEmployeeSalaryStatementParams) bindYearMonth(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("year_month", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("year_month", "query", raw); err != nil {
		return err
	}
	o.YearMonth = raw

	return nil
}
