// Code generated by go-swagger; DO NOT EDIT.

package get_salary_statement_for_employee

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetEmployeeSalaryStatementOKCode is the HTTP code returned for type GetEmployeeSalaryStatementOK
const GetEmployeeSalaryStatementOKCode int = 200

/*
GetEmployeeSalaryStatementOK OK

swagger:response getEmployeeSalaryStatementOK
*/
type GetEmployeeSalaryStatementOK struct {
}

// NewGetEmployeeSalaryStatementOK creates GetEmployeeSalaryStatementOK with default headers values
func NewGetEmployeeSalaryStatementOK() *GetEmployeeSalaryStatementOK {

	return &GetEmployeeSalaryStatementOK{}
}

// WriteResponse to the client
func (o *GetEmployeeSalaryStatementOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
