services:
  payroll-management:
    build: .
    command: ["/bin/sh", "-c", "go run /usr/src/app/main.go && /bin/sh"]
    tty: true
    working_dir: /usr/src/app
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./:/usr/src/app
    container_name: payroll_management_container
    ports:
    - 8080:8080
  db:
    image: mysql:8.0
    environment:
    - MYSQL_DATABASE=develop_db
    - MYSQL_ROOT_PASSWORD=password
    # how to write ports? : https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports
    ports:
    - 3306:3306
    container_name: db_container
    volumes:
    - ./db-container:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD
  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 7890:80
    environment:
    # when set to 1 connection to the arbitrary server will be allowed
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    container_name: phpmyadmin_container