// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger",
    "version": "0.1.0"
  },
  "paths": {
    "/employee/salary_statement": {
      "get": {
        "description": "従業員が特定の年月の給料明細書を取得するためのAPI",
        "tags": [
          "get_salary_statement_for_employee"
        ],
        "parameters": [
          {
            "type": "string",
            "format": "yyyy-MM",
            "description": "取得しようとしている給料明細書の年月",
            "name": "year_month",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Swagger",
    "version": "0.1.0"
  },
  "paths": {
    "/employee/salary_statement": {
      "get": {
        "description": "従業員が特定の年月の給料明細書を取得するためのAPI",
        "tags": [
          "get_salary_statement_for_employee"
        ],
        "parameters": [
          {
            "type": "string",
            "format": "yyyy-MM",
            "description": "取得しようとしている給料明細書の年月",
            "name": "year_month",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
  }
}`))
}
