// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SalaryStatementRequest salary statement request
//
// swagger:model salaryStatementRequest
type SalaryStatementRequest struct {

	// amount of deduction
	// Required: true
	AmountOfDeduction *int32 `json:"amount_of_deduction"`

	// amount of earning
	// Required: true
	AmountOfEarning *int32 `json:"amount_of_earning"`

	// individual deduction details
	// Required: true
	IndividualDeductionDetails []*SalaryStatementRequestIndividualDeductionDetailsItems0 `json:"individual_deduction_details"`

	// individual earning details
	// Required: true
	IndividualEarningDetails []*SalaryStatementRequestIndividualEarningDetailsItems0 `json:"individual_earning_details"`

	// mailaddress
	// Required: true
	Mailaddress *string `json:"mailaddress"`

	// month
	// Required: true
	Month *int64 `json:"month"`

	// nominal
	// Required: true
	Nominal *string `json:"nominal"`

	// nominal of deduction
	// Required: true
	NominalOfDeduction *string `json:"nominal_of_deduction"`

	// nominal of earning
	// Required: true
	NominalOfEarning *string `json:"nominal_of_earning"`

	// payday
	// Required: true
	// Format: date-time
	Payday *strfmt.DateTime `json:"payday"`

	// target period
	// Required: true
	TargetPeriod *string `json:"target_period"`

	// year
	// Required: true
	Year *int64 `json:"year"`
}

// Validate validates this salary statement request
func (m *SalaryStatementRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmountOfDeduction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAmountOfEarning(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndividualDeductionDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndividualEarningDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMailaddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMonth(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNominal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNominalOfDeduction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNominalOfEarning(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayday(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetPeriod(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateYear(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SalaryStatementRequest) validateAmountOfDeduction(formats strfmt.Registry) error {

	if err := validate.Required("amount_of_deduction", "body", m.AmountOfDeduction); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateAmountOfEarning(formats strfmt.Registry) error {

	if err := validate.Required("amount_of_earning", "body", m.AmountOfEarning); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateIndividualDeductionDetails(formats strfmt.Registry) error {

	if err := validate.Required("individual_deduction_details", "body", m.IndividualDeductionDetails); err != nil {
		return err
	}

	for i := 0; i < len(m.IndividualDeductionDetails); i++ {
		if swag.IsZero(m.IndividualDeductionDetails[i]) { // not required
			continue
		}

		if m.IndividualDeductionDetails[i] != nil {
			if err := m.IndividualDeductionDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("individual_deduction_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("individual_deduction_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SalaryStatementRequest) validateIndividualEarningDetails(formats strfmt.Registry) error {

	if err := validate.Required("individual_earning_details", "body", m.IndividualEarningDetails); err != nil {
		return err
	}

	for i := 0; i < len(m.IndividualEarningDetails); i++ {
		if swag.IsZero(m.IndividualEarningDetails[i]) { // not required
			continue
		}

		if m.IndividualEarningDetails[i] != nil {
			if err := m.IndividualEarningDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("individual_earning_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("individual_earning_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SalaryStatementRequest) validateMailaddress(formats strfmt.Registry) error {

	if err := validate.Required("mailaddress", "body", m.Mailaddress); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateMonth(formats strfmt.Registry) error {

	if err := validate.Required("month", "body", m.Month); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateNominal(formats strfmt.Registry) error {

	if err := validate.Required("nominal", "body", m.Nominal); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateNominalOfDeduction(formats strfmt.Registry) error {

	if err := validate.Required("nominal_of_deduction", "body", m.NominalOfDeduction); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateNominalOfEarning(formats strfmt.Registry) error {

	if err := validate.Required("nominal_of_earning", "body", m.NominalOfEarning); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validatePayday(formats strfmt.Registry) error {

	if err := validate.Required("payday", "body", m.Payday); err != nil {
		return err
	}

	if err := validate.FormatOf("payday", "body", "date-time", m.Payday.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateTargetPeriod(formats strfmt.Registry) error {

	if err := validate.Required("target_period", "body", m.TargetPeriod); err != nil {
		return err
	}

	return nil
}

func (m *SalaryStatementRequest) validateYear(formats strfmt.Registry) error {

	if err := validate.Required("year", "body", m.Year); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this salary statement request based on the context it is used
func (m *SalaryStatementRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIndividualDeductionDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIndividualEarningDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SalaryStatementRequest) contextValidateIndividualDeductionDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IndividualDeductionDetails); i++ {

		if m.IndividualDeductionDetails[i] != nil {
			if err := m.IndividualDeductionDetails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("individual_deduction_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("individual_deduction_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SalaryStatementRequest) contextValidateIndividualEarningDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IndividualEarningDetails); i++ {

		if m.IndividualEarningDetails[i] != nil {
			if err := m.IndividualEarningDetails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("individual_earning_details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("individual_earning_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SalaryStatementRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SalaryStatementRequest) UnmarshalBinary(b []byte) error {
	var res SalaryStatementRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SalaryStatementRequestIndividualDeductionDetailsItems0 salary statement request individual deduction details items0
//
// swagger:model SalaryStatementRequestIndividualDeductionDetailsItems0
type SalaryStatementRequestIndividualDeductionDetailsItems0 struct {

	// amount of deduction detail
	AmountOfDeductionDetail int32 `json:"amount_of_deduction_detail,omitempty"`

	// nominal
	Nominal string `json:"nominal,omitempty"`
}

// Validate validates this salary statement request individual deduction details items0
func (m *SalaryStatementRequestIndividualDeductionDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this salary statement request individual deduction details items0 based on context it is used
func (m *SalaryStatementRequestIndividualDeductionDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SalaryStatementRequestIndividualDeductionDetailsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SalaryStatementRequestIndividualDeductionDetailsItems0) UnmarshalBinary(b []byte) error {
	var res SalaryStatementRequestIndividualDeductionDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SalaryStatementRequestIndividualEarningDetailsItems0 salary statement request individual earning details items0
//
// swagger:model SalaryStatementRequestIndividualEarningDetailsItems0
type SalaryStatementRequestIndividualEarningDetailsItems0 struct {

	// amount of earning detail
	AmountOfEarningDetail int32 `json:"amount_of_earning_detail,omitempty"`

	// nominal
	Nominal string `json:"nominal,omitempty"`
}

// Validate validates this salary statement request individual earning details items0
func (m *SalaryStatementRequestIndividualEarningDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this salary statement request individual earning details items0 based on context it is used
func (m *SalaryStatementRequestIndividualEarningDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SalaryStatementRequestIndividualEarningDetailsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SalaryStatementRequestIndividualEarningDetailsItems0) UnmarshalBinary(b []byte) error {
	var res SalaryStatementRequestIndividualEarningDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
